name: GitHub Actions Build and Deploy

# 触发条件
on:
  # 手动触发
  workflow_dispatch:
  # push 到指定分支
  push:
    branches:
      - main1
    # 只在下列路径变更时触发
    # paths:
    #   - 'docs/**'
    #   - 'package.json'

# 设置权限
permissions:
  contents: write

# 设置上海时区
env:
  TZ: Asia/Shanghai

# 任务
jobs:
  build:
    runs-on: ubuntu-latest # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    steps:
      - name: 拉取代码 # 步骤名字
        uses: actions/checkout@master # 使用 actions/checkout 库拉取最新源码
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: 项目安装依赖
        run: pnpm install --frozen-lockfile

      - name: 项目打包构建
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm build
 
      # 部署到GitHub Pages - 也就是将打包内容发布到GitHub Pages
      - name: Deploy
        # 使用别人写好的 actions去部署（将打包文件部署到指定分支上）
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        # 自定义环境变量
        with:
          # 指定仓库：你要发布的仓库路径名
          repository-name: abp-vnext-pro/abp-vnext-pro.github.io
          # 部署到 deploy-pages 分支，也就是部署后提交到那个分支
          branch: gh-pages
          # 填写打包好的目录名称路径，本项目配置在根目录
          folder: .vitepress/dist